heiwa_frontend/views/forum/__init__.py
import http.client
import typing
import uuid

import flask

from heiwa_frontend import utils

__all__ = [
	"forum_blueprint",
	"list_",
	"parse_category",
	"parse_forum",
	"parse_thread",
	"view"
]


forum_blueprint = flask.Blueprint(
	"forum",
	__name__,
	url_prefix="/forums"
)


def parse_category(
	category: typing.Dict,
	parse_forums: bool = True
) -> typing.List[typing.Dict]:
	forums = utils.request(
		flask.g.session,
		"query",
		"forums",
		json={
			"order": {
				"by": "order",
				"asc": True
			},
			"limit": 512,
			"filter": {
				"$equals": {"category_id": category["id"]}
			}
		}
	).json()

	raw_forums = forums.copy()

	category["forums"] = [
		parse_forum(forum) if parse_forums else forum
		for forum in forums
	]

	return raw_forums


def parse_forum(forum: typing.Dict) -> typing.Dict:
	# Don't need any allowed actions here. The editing will be done through
	# an admin panel (TODO), and subscriptions will happen on the thread
	# listing.

	latest_threads = utils.request(
		flask.g.session,
		"query",
		"threads",
		json={
			"order": {
				"by": "creation_timestamp",
				"asc": False
			},
			"limit": 1,
			"filter": {
				"$equals": {"forum_id": forum["id"]}
			}
		}
	).json()

	if len(latest_threads) == 0:
		forum["$latest_thread"] = None
		return forum

	latest_thread = latest_threads[0]

	forum["$latest_thread"] = latest_thread

	forum["$latest_thread"]["$author"] = utils.request(
		flask.g.session,
		"get",
		f"users/{latest_thread['user_id']}"
	).json()

	return forum


def parse_thread(thread: typing.Dict) -> typing.Dict:
	thread["$author"] = utils.request(
		flask.g.session,
		"get",
		f"users/{thread['user_id']}"
	).json()

	thread["$allowed_actions"] = utils.request(
		flask.g.session,
		"get",
		f"threads/{thread['id']}/allowed-actions"
	).json()

	latest_posts = utils.request(
		flask.g.session,
		"query",
		"posts",
		json={
			"order": {
				"by": "creation_timestamp",
				"asc": False
			},
			"limit": 1,
			"filter": {
				"$equals": {"thread_id": thread["id"]}
			}
		}
	).json()

	if len(latest_posts) == 0:
		thread["$latest_post"] = None
		return thread

	thread["$latest_post"] = latest_posts[0]

	thread["$latest_post"]["$author"] = utils.request(
		flask.g.session,
		"get",
		f"users/{thread['$latest_post']['user_id']}"
	).json()

	return thread


@forum_blueprint.route("", methods=["GET"])
@utils.authentication_required
@utils.full_view()
def list_() -> typing.Tuple[flask.Response, int]:
	futures = []

	uncategorized_forums = utils.request(
		flask.g.session,
		"query",
		"forums",
		json={
			"order": {
				"by": "order",
				"asc": True
			},
			"limit": 512,
			"filter": {
				"$and": [
					{"$equals": {"parent_forum_id": None}},
					{"$equals": {"category_id": None}}
				]
			}
		}
	).json()

	raw_forums_and_categories = uncategorized_forums.copy()

	if not len(uncategorized_forums) == 0:
		futures += [
			flask.current_app.executor.submit(
				parse_forum,
				forum
			)
			for forum in uncategorized_forums
		]

	categories = utils.request(
		flask.g.session,
		"query",
		"categories",
		json={
			"order": {
				"by": "order",
				"asc": True
			},
			"limit": 512,
			"filter": {
				"$equals": {"forum_id": None}
			}
		}
	).json()

	raw_forums_and_categories += categories

	if not len(categories) == 0:
		futures += [
			flask.current_app.executor.submit(
				parse_category,
				category
			)
			for category in categories
		]

	utils.handle_futures(futures)

	for future in futures:
		raw_forums_and_categories.append(future.result())

	return flask.render_template(
		"forum_list.html",
		categories=categories,
		uncategorized_forums=uncategorized_forums,
		raw_forums_and_categories=raw_forums_and_categories
	), http.client.OK


@forum_blueprint.route("/<uuid:id_>", methods=["GET", "POST"])
@utils.authentication_required
@utils.full_view()
def view(id_: uuid.UUID) -> typing.Tuple[flask.Response, int]:
	disable_forum_subscription_cache = False

	if flask.request.method == "POST":
		subscribe = flask.request.args.get("subscribe")

		if subscribe is not None:
			if subscribe == "true":
				method = "put"
			elif subscribe == "false":
				method = "delete"

			utils.request(
				flask.g.session,
				method,
				f"forums/{id_}/subscription"
			)

		disable_forum_subscription_cache = True

	futures = []

	forum = utils.request(
		flask.g.session,
		"get",
		f"forums/{id_}"
	).json()

	raw_forum_and_threads = [forum.copy()]

	forum["$allowed_actions"] = utils.request(
		flask.g.session,
		"get",
		f"forums/{id_}/allowed-actions"
	).json()

	if "edit_subscription" in forum["$allowed_actions"]:
		def get_subscription() -> dict:
			return utils.request(
				flask.g.session,
				"get",
				f"forums{id_}/subscription"
			).json()

		if disable_forum_subscription_cache:
			with flask.g.session.cache_disabled():
				forum["$is_subscribed"] = get_subscription()
		else:
			forum["$is_subscribed"] = get_subscription()

	forum["$child_categories"] = utils.request(
		flask.g.session,
		"query",
		"categories",
		json={
			"order": {
				"by": "order",
				"asc": True
			},
			"limit": 512,
			"filter": {
				"$equals": {"forum_id": forum["id"]}
			}
		}
	).json()

	forum["$child_forums_uncategorized"] = utils.request(
		flask.g.session,
		"query",
		"forums",
		json={
			"order": {
				"by": "order",
				"asc": True
			},
			"limit": 512,
			"filter": {
				"$equals": {"parent_forum_id": forum["id"]}
			}
		}
	).json()

	if not len(forum["$child_categories"]) == 0:
		futures += [
			flask.current_app.executor.submit(
				parse_category,
				category,
				parse_forums=False
			)
			for category in forum["$child_categories"]
		]

	forum["$threads"] = []

	threads = utils.request(
		flask.g.session,
		"query",
		"threads",
		json={
			"limit": 512,
			"filter": {
				"$and": [
					{"$equals": {"forum_id": forum["id"]}},
					{"$equals": {"is_pinned": True}}
				]
			}
		}
	).json()

	raw_forum_and_threads += threads

	# Pinned threads first
	forum["$threads"] += [
		parse_thread(thread)
		for thread in threads
	]

	forum["$threads"] += [
		parse_thread(thread)
		for thread in (
			utils.request(
				flask.g.session,
				"query",
				"threads",
				json={
					"limit": 25,
					"filter": {
						"$and": [
							{"$equals": {"forum_id": forum["id"]}},
							{"$equals": {"is_pinned": False}}
						]
					}
				}
			).json()
		)
	]

	if len(forum["$threads"]) != 0:
		futures += [
			flask.current_app.executor.submit(
				parse_thread,
				thread
			)
			for thread in forum["$threads"]
		]

	if len(futures) != 0:
		utils.handle_futures(futures)

	return flask.render_template(
		"forum_view.html",
		forum=forum,
		raw_forum_and_threads=raw_forum_and_threads
	), http.client.OK

heiwa_frontend/views/message/__init__.py
import base64
import binascii
import http.client
import json
import typing
import uuid

import flask
import flask_babel
import flask_wtf
import wtforms
import wtforms.validators

from heiwa_frontend import utils

__all__ = [
	"MessageForm",
	"create",
	"message_blueprint"
]


message_blueprint = flask.Blueprint(
	"message",
	__name__,
	url_prefix="/messages"
)


def validate_is_base64(
	form: flask_wtf.FlaskForm,
	field: wtforms.Field
) -> None:
	try:
		base64.b64decode(
			field.data,
			validate=True
		)
	except binascii.Error as exception:
		raise wtforms.validators.ValidationError from exception


def validate_is_uuid(
	form: flask_wtf.FlaskForm,
	field: wtforms.Field
) -> None:
	try:
		uuid.UUID(field.data)
	except ValueError as exception:
		raise wtforms.validators.ValidationError from exception


class MessageForm(flask_wtf.FlaskForm):
	receiver_id = wtforms.HiddenField(
		validators=[
			wtforms.validators.InputRequired(),
			validate_is_uuid
		]
	)

	directory = wtforms.SelectField(
		flask_babel.lazy_gettext("Directory")
	)

	encrypted_session_key = wtforms.HiddenField(
		validators=[
			wtforms.validators.InputRequired(),
			validate_is_base64
		]
	)

	iv = wtforms.HiddenField(
		validators=[
			wtforms.validators.InputRequired(),
			validate_is_base64
		]
	)

	tag = wtforms.HiddenField(
		validators=[
			wtforms.validators.InputRequired(),
			validate_is_base64
		]
	)

	encrypted_content = wtforms.HiddenField(
		validators=[
			wtforms.validators.InputRequired(),
			validate_is_base64
		]
	)


@message_blueprint.route("/", methods=["GET"])
@utils.authentication_required
@utils.full_view()
def list_() -> typing.Tuple[flask.Response, int]:
	directories = (
		# These ones first!
		[
			{"name": flask_babel.gettext("Received"), "$type": "received"},
			{"name": flask_babel.gettext("Sent"), "$type": "sent"}
		]
		+ utils.request(
			flask.g.session,
			"query",
			"messages/directories",
			json={
				"limit": 512,
				"order": {
					"by": "order",
					"asc": False
				}
			}
		).json()
	)

	return flask.render_template(
		"message_list.html",
		directories=directories
	), http.client.OK


@message_blueprint.route("/create", methods=["GET", "POST"])
@utils.authentication_required
@utils.full_view()
def create() -> typing.Union[
	flask.Response,
	typing.Tuple[flask.Response, int]
]:
	form = MessageForm()

	directories = utils.request(
		flask.g.session,
		"query",
		"messages/directories",
		json={
			"limit": 512,
			"order": {
				"by": "order",
				"asc": False
			}
		}
	).json()

	choices = [
		(directory["id"], directory["name"])
		for directory in directories
	]

	choices.append(
		("", flask_babel.gettext("Sent (default directory)"))
	)

	form.directory.choices = choices

	if form.validate_on_submit():
		utils.request(
			flask.g.session,
			"post",
			"messages",
			json={
				"receiver_id": form.receiver_id.data,
				"sender_directory_id": (
					form.directory.data
					if form.directory.data != ""
					else None
				),
				"encrypted_session_key": form.encrypted_session_key.data,
				"iv": form.iv.data,
				"tag": form.tag.data,
				"encrypted_content": form.encrypted_content.data
			}
		)

		return "TODO (success, no errors!)"
	else:
		return flask.render_template(
			"message_create.html",
			form=form,
			json_current_user=json.dumps(flask.g.user)
		), http.client.OK

heiwa_frontend/views/meta/__init__.py
import http.client
import io
import email
import typing

import flask

from heiwa_frontend import utils

__all__ = [
	"meta_blueprint",
	"view_icon"
]


meta_blueprint = flask.Blueprint(
	"meta",
	__name__,
	url_prefix="/meta"
)


@meta_blueprint.route("/icon", methods=["GET"])
def view_icon() -> typing.Union[
	flask.Response,
	typing.Tuple[flask.Response, int]
]:
	icon = utils.request(
		flask.g.session,
		"get",
		"meta/icon"
	)

	if icon.headers["Content-Type"] == "application/ld+json":
		return flask.redirect(
			flask.url_for(
				"static",
				filename="images/icon.png"
			)
		)

	return flask.send_file(
		io.BytesIO(icon.content),
		mimetype=icon.headers["Content-Type"],
		as_attachment=False,
		download_name=icon.headers["Content-Disposition"].split("filename=")[1],
		last_modified=email.utils.parsedate_to_datetime(
			icon.headers["Last-Modified"]
		).timestamp()
	), http.client.OK

heiwa_frontend/views/tos/__init__.py
import http.client
import typing

import flask

from heiwa_frontend import utils

__all__ = [
	"tos_blueprint",
	"view"
]


tos_blueprint = flask.Blueprint(
	"tos",
	__name__,
	url_prefix="/tos"
)


@tos_blueprint.route("", methods=["GET"])
@utils.full_view(anonymous=True)
def view() -> typing.Tuple[flask.Response, int]:
	tos = utils.request(
		flask.g.session,
		"get",
		"meta/info",
		ignore_token=True
	).json()["tos"]

	return flask.render_template(
		"tos.html",
		tos=tos
	), http.client.OK

heiwa_frontend/views/user/__init__.py
import http.client
import io
import email
import typing
import uuid

import flask

from heiwa_frontend import utils

__all__ = [
	"user_blueprint",
	"view",
	"view_avatar",
	"view_public_key"
]


user_blueprint = flask.Blueprint(
	"user",
	__name__,
)


@user_blueprint.route("/users/<uuid:id_>/avatar", methods=["GET"])
@utils.authentication_required
def view_avatar(id_: uuid.UUID) -> typing.Union[
	flask.Response,
	typing.Tuple[flask.Response, int]
]:
	avatar = utils.request(
		flask.g.session,
		"get",
		f"users/{id_}/avatar"
	)

	if not avatar.headers["Content-Type"].startswith("image/"):
		# Not an image, very likely :data:`None`
		return flask.redirect(
			flask.url_for(
				"static",
				filename="images/default_avatar.svg"
			)
		)

	return flask.send_file(
		io.BytesIO(avatar.content),
		mimetype=avatar.headers["Content-Type"],
		as_attachment=False,
		download_name=avatar.headers["Content-Disposition"].split("filename=")[1],
		last_modified=email.utils.parsedate_to_datetime(
			avatar.headers["Last-Modified"]
		).timestamp()
	), http.client.OK


@user_blueprint.route("/users/<uuid:id_>", methods=["GET"])
@utils.authentication_required
@utils.full_view()
def view(id_: uuid.UUID) -> typing.Tuple[flask.Response, int]:
	user = utils.request(
		flask.g.session,
		"get",
		f"users/{id_}"
	).json()

	raw_user = user.copy()

	user["$allowed_actions"] = utils.request(
		flask.g.session,
		"get",
		f"users/{user['id']}/allowed-actions"
	).json()

	if user["thread_count"] != 0:
		user["$threads"] = utils.request(
			flask.g.session,
			"query",
			"threads",
			json={
				"limit": 3,
				"filter": {
					"$equals": {"user_id": user["id"]}
				}
			}
		).json()

	if user["post_count"] != 0:
		user["$posts"] = utils.request(
			flask.g.session,
			"query",
			"posts",
			json={
				"limit": 5,
				"filter": {
					"$equals": {"user_id": user["id"]}
				}
			}
		).json()

	return flask.render_template(
		"user_view.html",
		user=user,
		raw_user=raw_user
	), http.client.OK


@user_blueprint.route("/users/<uuid:id_>/public-key", methods=["GET"])
@user_blueprint.route("/self/public-key", methods=["GET"])
@utils.authentication_required
@utils.full_view()
def view_public_key(
	id_: typing.Union[None, uuid.UUID]
) -> typing.Tuple[flask.Response, int]:
	if id_ is None:
		id_ = flask.g.user.id

	user = utils.request(
		flask.g.session,
		"get",
		f"users/{id_}"
	).json()

	return flask.render_template(
		"user_view_public_key.html",
		user=user
	), http.client.OK

heiwa_frontend/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>
			{% block current_name %}{% endblock %}
			{% if "meta_info" in g %}
				{{ gettext(" - ") }}
				{{ g.meta_info["name"] }}
			{% endif %}
		</title>
		<meta encoding="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link
			rel="stylesheet"
			type="text/css"
			href="{{ url_for('static', filename='css/main.css') }}"
		>
		<link
			rel="stylesheet"
			type="text/css"
			href="{{ url_for('static', filename='fa/css/all.css') }}"
		>
		<link
			rel="stylesheet"
			type="text/css"
			href="{{ url_for('static', filename='css/fonts.css') }}"
		>
		<link
			rel="icon"
			href="{{ url_for('meta.view_icon') }}"
		>
		<script type="text/javascript">
			const API_URL = "{{ config['PUBLIC_API_URL'] }}";
		</script>
		<script
			type="text/javascript"
			src="{{ url_for('static', filename='js/locales/en.js') }}"
		></script>
		{% block head %}{% endblock %}
		{% if config["BABEL_DEFAULT_LOCALE"] != "en" %}
			<script
				type="text/javascript"
				src="{{
					url_for(
						'static',
						filename='js/locales/' + config['BABEL_DEFAULT_LOCALE'] + '.js'
					)
				}}"
			></script>
		{% endif %}
	</head>
	<body>
		<header>
			{% if "meta_info" in g %}
				<div class="header-left">
					<a
						class="header-item"
						href="{{ url_for('forum.list_') }}"
					>
						{{ g.meta_info["name"] }}
					</a>
				</div>
			{% endif %}
			<div class="header-center">
				<div class="header-item highlighted">
					{{ self.current_name() }}
				</div>
			</div>
			{% if "user" in g %}
				<div class="header-right">
					<div class="dropdown" tabindex="0">
						<div class="dropdown-button header-item">
							{% if g.user["name"] == "" or g.user["name"] is none %}
								{% if g.user["registered_by"] == "guest" %}
									{{ gettext("Guest") }}
								{% else %}
									{{ gettext("Unnamed") }}
								{% endif %}
							{% else %}
								{{ g.user["name"] }}
							{% endif %}
						</div>
						<div class="dropdown-content">
							<a
								class="dropdown-item"
								href="#"
							>
								{% if g.user["registered_by"] == "guest" %}
									{{ gettext("Your temporary profile") }}
								{% else %}
									{{ gettext("Your profile") }}
								{% endif %}
							</a>
							
							{% if "view" in g.message_allowed_actions %}
								<a
									class="dropdown-item"
									href="{{ url_for('message.list_') }}"
								>
									{{ gettext("Messages") }}
									
									{% if g.unread_message_count != 0 %}
										<span class="message-unread-circle">
											{{ g.unread_message_count }}{% if g.unread_message_count == 501 %}{{ gettext("+") }}{% endif %}
										</span>
									{% endif %}
								</a>
							{% endif %}
							
							<a
								class="dropdown-item"
								href="#"
							>{{ gettext("Options") }}</a>
							{% if g.user.registered_by == "guest" %}
								<a
									class="dropdown-item"
									href="{{ url_for('account.login') }}"
								>{{ gettext("Log in") }}</a>
							{% else %}
								<a
									class="dropdown-item"
									href="{{ url_for('account.logout') }}"
								>{{ gettext("Log out") }}</a>
							{% endif %}
							<a
								class="dropdown-item"
								href="{{ url_for('account.register') }}"
							>{{ gettext("Register") }}</a>
						</div>
					</div>
				</div>
			{% endif %}
		</header>
		<main>{% block content %}{% endblock %}</main>
		<footer>
			
		</footer>
	</body>
</html>

heiwa_frontend/templates/error.html
{% extends 'base.html' %}

{% block current_name %}{{ gettext("Error") }}{% endblock %}

{% block content %}
<section class="window main-center">
	<h1>{{ exception.name }}</h1>
	<p>
		{{ exception.description }}
	</p>
</section>
{% endblock %}

heiwa_frontend/templates/file_create.html
<form method="post" enctype="multipart/form-data">
	{{ form.hidden_tag() }}
	{{ form.file_ }}
	{{ form.submit }}
</form>

heiwa_frontend/templates/forum_list.html
{% extends 'base.html' %}

{% macro render_forum(forum) -%}
	<section class="forum-wrapper">
		<div class="forum-name-desc">
			<h3>
				<a href="{{ url_for('forum.view', id_=forum['id']) }}">
					{{ forum["name"] }}
				</a>
			</h3>
			{% if forum["description"] %}
				<p class="text-secondary">{{ forum["description"] }}</p>
			{% endif %}
		</div>

		<div class="forum-counters">
			<div>
				{% if forum["thread_count"] == 0 %}
					<span class="text-secondary">
						{{ gettext("No threads") }}
					</span>
				{% else %}
					{{ forum["thread_count"]|human_number }}
					<span class="text-secondary">
						{{ ngettext("Thread", "Threads", forum["thread_count"]) }}
					</span>
				{% endif %}
			</div>
			{% if forum["thread_count"] != 0 %}
				<div>
					{% if forum["post_count"] == 0 %}
						<span class="text-secondary">
							{{ gettext("No posts") }}
						</span>
					{% elif forum["thread_count"] != 0 %}
						{{ forum["post_count"]|human_number }}
						<span class="text-secondary">
							{{ ngettext("Post", "Posts", forum["post_count"]) }}
						</span>
					{% endif %}
				</div>
			{% endif %}
		</div>

		<div class="forum-latest-thread">
			{% if forum["$latest_thread"] %}
				<div>
					<div>
						<a href="#">
							{{ forum["$latest_thread"]["name"] }}
						</a>
					</div>
					<div class="text-secondary">
						{{ forum["$latest_thread"]["creation_timestamp"]|isotime_difference }}
					</div>
				</div>
				<a href="{{ url_for('user.view', id_=forum['$latest_thread']['user_id']) }}">
					<img
						width="50"
						src="{{ url_for('user.view_avatar', id_=forum['$latest_thread']['user_id']) }}"
						alt="{{ gettext('Thread author\'s avatar') }}"
					>
				 </a>
			{% else %}
				<span class="forum-no-threads text-secondary">
					{{ gettext("No threads") }}
				</span>
			{% endif %}
		</div>
	</section>
{%- endmacro %}

{% block current_name %}{{ gettext("Forums") }}{% endblock %}

{% block head %}<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/forum_list.css') }}"
>
<script type="application/ld+json">
	{% for object in raw_forums_and_categories %}
		{{ object }}
	{% endfor %}
</script>{% endblock %}

{% block content %}
	{% for category in categories %}
		<section class="window main-center">
			<h2>{{ category["name"] }}</h2>
			{% if category["description"] %}
				<p>{{ category["description"] }}</p>
			{% endif %}
			<hr>

			{% if category["forums"]|length != 0 %}
				{% for forum in category["forums"] %}
					{{ render_forum(forum) }}
				{% endfor %}
			{% else %}
				<span class="text-secondary">
					{{ gettext("No forums") }}
				</span>
			{% endif %}
		</section>
	{% endfor %}

	{% if uncategorized_forums|length != 0 %}
		<section class="window main-center">
			{% if categories|length != 0 %}
				<h2>{{ gettext("Uncategorized") }}</h2>
				<hr>
			{% endif %}

			{% for forum in uncategorized_forums %}
				{{ render_forum(forum) }}
			{% endfor %}
		</section>
	{% endif %}
{% endblock %}

heiwa_frontend/templates/logout.html
{% extends 'base.html' %}

{% block current_name %}{{ gettext("Logout") }}{% endblock %}

{% block head %}<script
	type="text/javascript"
	src="{{ url_for('static', filename='js/logout.js') }}"
></script>{% endblock %}

{% block content %}
	<section class="window main-center">
		{% if not g.known_js_disabled %}
			<noscript>
				<div>
					<h1>{{ gettext("Warning!") }}</h1>
					<p>{{
						gettext(
							"JavaScript is disabled. If it was enabled in the past, your "
							"browser may still have your private key stored in its local "
							"storage. This could potentially allow others to read your "
							"private messages."
						)
					}}</p>
				</div>
				<hr>
			</noscript>
		{% endif %}
		<p>
			{{ gettext("You have been logged out.") }}
			<a
				href="{{ url_for('forum.list_') }}"
			>{{ gettext("If you're not automatically redirected, click here.") }}</a>
		</p>
		<script>
			// Is this a waste of time? But, at the same time, we want to give the
			// users a bit of time to read the text. And this page does need to be
			// loaded, due to the JS private key removal.
			setTimeout(function () {
				window.location.replace("{{ url_for('forum.list_') }}");
			}, 1000);
		</script>
	</section>
{% endblock %}

heiwa_frontend/templates/message_list.html
{% extends 'base.html' %}

{% block current_name %}{{ gettext("Messages") }}{% endblock %}

{% block head %}<script
	type="text/javascript"
	src="{{ url_for('static', filename='js/forge.js') }}"
></script>
<script
	type="text/javascript"
	src="{{ url_for('static', filename='js/api.js') }}"
></script>
<script
	type="text/javascript"
	src="{{ url_for('static', filename='js/message_list.js') }}"
></script>

<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/message_list.css') }}"
>{% endblock %}

{% block content %}
	<section class="main-center">
		<section id="manual-privkey-input-wrapper" class="window" style="display:none">
			<h1>
				{{ gettext("Please generate a private key, or enter one.") }}
			</h1>
			<p>
				{{
					gettext(
						"This is required to receive encrypted messages. To generate and set "
						"one permanently, use the "
					)
				}}
				<a
					href="#"
				>{{ gettext("TODO page") }}</a>{{ gettext(".") }}
			</p>
			<textarea id="manual-privkey-input" autocomplete="off"></textarea>
			<button id="manual-private-key-set">{{ gettext("Set") }}</button>
		</section>

		<section id="privkey-decrypt-wrapper" class="window" style="display:none">
			<p>
				{{ gettext("Please enter the password to decrypt your private key.") }}
			</p>
			<input type="password" id="privkey-password-input">
			<button id="privkey-decrypt">{{ gettext("Decrypt") }}</button>
		</section>

		<section id="new-message-wrapper">
			<a
				class="button"
				href="{{ url_for('message.create') }}"
			>{{ gettext("New message") }}</a>
		</section>

		<section id="message-window-wrapper" class="window" style="display:none">
			<ul id="message-directory-list-wrapper">
				{% for directory in directories %}
					<li
						class="message-directory"
						data-is-selected="false"
						data-name="{{ directory['name'] }}"
						{% if "id" in directory %}
							data-is-default="false"
							id="message-directory-{{ directory.id }}"
						{% else %}
							data-is-default="true"
							data-default-type="{{ directory['$type'] }}"
						{% endif %}
					>
						<div class="message-directory-name">{{ directory["name"] }}</div>
					</li>
				{% endfor %}
			</ul>

			<section id="message-view-wrapper"></section>
		</section>
	</section>
{% endblock %}

heiwa_frontend/templates/register.html
{% extends 'base.html' %}

{% block current_name %}{{ gettext("Register") }}{% endblock %}

{% block head %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/register.css') }}"
>{% endblock %}

{% block content %}
	<section class="window main-center">
		<h1>Register</h1>
		<form method="post" class="register-form">
			<div>
				{{
					form.email(
						size=32,
						placeholder=form.email.label.text
					)
				}}
			</div>
			<div>
				{{
					form.password(
						size=32,
						placeholder=form.password.label.text
					)
				}}
			</div>
			<div class="tos-wrapper">
				<a
					href="{{ url_for('tos.view') }}"
				>{{ gettext("Terms of service") }}</a>
			</div>
			<div>
				{{ form.submit }}
			</div>
		</form>
	</section>
{% endblock %}

heiwa_frontend/templates/tos.html
{% extends 'base.html' %}

{% block current_name %}{{ gettext("Terms of service") }}{% endblock %}

{% block content %}
	<section class="window main-center">
		<h1>Terms of service</h1>
		{{ tos|safe }}
	</section>
{% endblock %}

heiwa_frontend/templates/user_view.html
{% extends 'base.html' %}

{% block current_name %}
	{{ gettext("User") }}
	{{ gettext(" - ") }}
	{{ user["name"] }}
{% endblock %}

{% block head %}<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/user_view.css') }}"
>{% endblock %}

{% block content %}
	
{% endblock %}